// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notificationService.proto

package com.example.grpctest1;

/**
 * Protobuf type {@code com.example.grpctest1.ListNotificationRequest}
 */
public  final class ListNotificationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpctest1.ListNotificationRequest)
    ListNotificationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListNotificationRequest.newBuilder() to construct.
  private ListNotificationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListNotificationRequest() {
    page_ = 0;
    pageSize_ = 0;
    studentUserid_ = 0L;
    seen_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListNotificationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            page_ = input.readInt32();
            break;
          }
          case 16: {

            pageSize_ = input.readInt32();
            break;
          }
          case 24: {

            studentUserid_ = input.readInt64();
            break;
          }
          case 32: {

            seen_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_ListNotificationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_ListNotificationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpctest1.ListNotificationRequest.class, com.example.grpctest1.ListNotificationRequest.Builder.class);
  }

  public static final int PAGE_FIELD_NUMBER = 1;
  private int page_;
  /**
   * <code>int32 page = 1;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pageSize_;
  /**
   * <code>int32 pageSize = 2;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int STUDENTUSERID_FIELD_NUMBER = 3;
  private long studentUserid_;
  /**
   * <code>int64 studentUserid = 3;</code>
   */
  public long getStudentUserid() {
    return studentUserid_;
  }

  public static final int SEEN_FIELD_NUMBER = 4;
  private boolean seen_;
  /**
   * <code>bool seen = 4;</code>
   */
  public boolean getSeen() {
    return seen_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (page_ != 0) {
      output.writeInt32(1, page_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(2, pageSize_);
    }
    if (studentUserid_ != 0L) {
      output.writeInt64(3, studentUserid_);
    }
    if (seen_ != false) {
      output.writeBool(4, seen_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, page_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageSize_);
    }
    if (studentUserid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, studentUserid_);
    }
    if (seen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, seen_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpctest1.ListNotificationRequest)) {
      return super.equals(obj);
    }
    com.example.grpctest1.ListNotificationRequest other = (com.example.grpctest1.ListNotificationRequest) obj;

    boolean result = true;
    result = result && (getPage()
        == other.getPage());
    result = result && (getPageSize()
        == other.getPageSize());
    result = result && (getStudentUserid()
        == other.getStudentUserid());
    result = result && (getSeen()
        == other.getSeen());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + STUDENTUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStudentUserid());
    hash = (37 * hash) + SEEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSeen());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpctest1.ListNotificationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.ListNotificationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.ListNotificationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpctest1.ListNotificationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpctest1.ListNotificationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpctest1.ListNotificationRequest)
      com.example.grpctest1.ListNotificationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_ListNotificationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_ListNotificationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpctest1.ListNotificationRequest.class, com.example.grpctest1.ListNotificationRequest.Builder.class);
    }

    // Construct using com.example.grpctest1.ListNotificationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      page_ = 0;

      pageSize_ = 0;

      studentUserid_ = 0L;

      seen_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_ListNotificationRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpctest1.ListNotificationRequest getDefaultInstanceForType() {
      return com.example.grpctest1.ListNotificationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpctest1.ListNotificationRequest build() {
      com.example.grpctest1.ListNotificationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpctest1.ListNotificationRequest buildPartial() {
      com.example.grpctest1.ListNotificationRequest result = new com.example.grpctest1.ListNotificationRequest(this);
      result.page_ = page_;
      result.pageSize_ = pageSize_;
      result.studentUserid_ = studentUserid_;
      result.seen_ = seen_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpctest1.ListNotificationRequest) {
        return mergeFrom((com.example.grpctest1.ListNotificationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpctest1.ListNotificationRequest other) {
      if (other == com.example.grpctest1.ListNotificationRequest.getDefaultInstance()) return this;
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getStudentUserid() != 0L) {
        setStudentUserid(other.getStudentUserid());
      }
      if (other.getSeen() != false) {
        setSeen(other.getSeen());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpctest1.ListNotificationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpctest1.ListNotificationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 1;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder setPage(int value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 1;</code>
     */
    public Builder clearPage() {
      
      page_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private long studentUserid_ ;
    /**
     * <code>int64 studentUserid = 3;</code>
     */
    public long getStudentUserid() {
      return studentUserid_;
    }
    /**
     * <code>int64 studentUserid = 3;</code>
     */
    public Builder setStudentUserid(long value) {
      
      studentUserid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 studentUserid = 3;</code>
     */
    public Builder clearStudentUserid() {
      
      studentUserid_ = 0L;
      onChanged();
      return this;
    }

    private boolean seen_ ;
    /**
     * <code>bool seen = 4;</code>
     */
    public boolean getSeen() {
      return seen_;
    }
    /**
     * <code>bool seen = 4;</code>
     */
    public Builder setSeen(boolean value) {
      
      seen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool seen = 4;</code>
     */
    public Builder clearSeen() {
      
      seen_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpctest1.ListNotificationRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpctest1.ListNotificationRequest)
  private static final com.example.grpctest1.ListNotificationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpctest1.ListNotificationRequest();
  }

  public static com.example.grpctest1.ListNotificationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListNotificationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListNotificationRequest>() {
    @java.lang.Override
    public ListNotificationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListNotificationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListNotificationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListNotificationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpctest1.ListNotificationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

