// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notificationService.proto

package com.example.grpctest1;

public final class NotificationServiceOuterClass {
  private NotificationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpctest1_NotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpctest1_NotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpctest1_NotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpctest1_NotificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpctest1_ListNotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpctest1_ListNotificationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031notificationService.proto\022\025com.example" +
      ".grpctest1\"z\n\023NotificationRequest\022\024\n\014tem" +
      "plateCode\030\001 \001(\t\022\025\n\rstudentUserid\030\002 \001(\003\022\023" +
      "\n\013staffUserid\030\003 \001(\003\022\016\n\006option\030\004 \001(\t\022\021\n\tw" +
      "ithEmail\030\005 \001(\010\"x\n\024NotificationResponse\022\n" +
      "\n\002id\030\001 \001(\003\022\025\n\rstudentUserid\030\002 \001(\003\022\017\n\007con" +
      "tent\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\014\n\004seen\030\005 \001(\010\022\021\n" +
      "\twithEmail\030\006 \001(\010\"^\n\027ListNotificationRequ" +
      "est\022\014\n\004page\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\025\n\rs" +
      "tudentUserid\030\003 \001(\003\022\014\n\004seen\030\004 \001(\0102\375\001\n\023Not" +
      "ificationService\022m\n\020sendNotification\022*.c" +
      "om.example.grpctest1.NotificationRequest" +
      "\032+.com.example.grpctest1.NotificationRes" +
      "ponse\"\000\022w\n\024getListNotifications\022..com.ex" +
      "ample.grpctest1.ListNotificationRequest\032" +
      "+.com.example.grpctest1.NotificationResp" +
      "onse\"\0000\001B\031\n\025com.example.grpctest1P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpctest1_NotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpctest1_NotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpctest1_NotificationRequest_descriptor,
        new java.lang.String[] { "TemplateCode", "StudentUserid", "StaffUserid", "Option", "WithEmail", });
    internal_static_com_example_grpctest1_NotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpctest1_NotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpctest1_NotificationResponse_descriptor,
        new java.lang.String[] { "Id", "StudentUserid", "Content", "Url", "Seen", "WithEmail", });
    internal_static_com_example_grpctest1_ListNotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpctest1_ListNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpctest1_ListNotificationRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", "StudentUserid", "Seen", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
