// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notificationService.proto

package com.example.grpctest1;

public interface NotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpctest1.NotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 studentUserid = 2;</code>
   */
  long getStudentUserid();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string url = 4;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 4;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>bool seen = 5;</code>
   */
  boolean getSeen();

  /**
   * <code>bool withEmail = 6;</code>
   */
  boolean getWithEmail();
}
