// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notificationService.proto

package com.example.grpctest1;

/**
 * Protobuf type {@code com.example.grpctest1.NotificationRequest}
 */
public  final class NotificationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpctest1.NotificationRequest)
    NotificationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotificationRequest.newBuilder() to construct.
  private NotificationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotificationRequest() {
    templateCode_ = "";
    studentUserid_ = 0L;
    staffUserid_ = 0L;
    option_ = "";
    withEmail_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NotificationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            templateCode_ = s;
            break;
          }
          case 16: {

            studentUserid_ = input.readInt64();
            break;
          }
          case 24: {

            staffUserid_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            option_ = s;
            break;
          }
          case 40: {

            withEmail_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_NotificationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_NotificationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpctest1.NotificationRequest.class, com.example.grpctest1.NotificationRequest.Builder.class);
  }

  public static final int TEMPLATECODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object templateCode_;
  /**
   * <code>string templateCode = 1;</code>
   */
  public java.lang.String getTemplateCode() {
    java.lang.Object ref = templateCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      templateCode_ = s;
      return s;
    }
  }
  /**
   * <code>string templateCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTemplateCodeBytes() {
    java.lang.Object ref = templateCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      templateCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENTUSERID_FIELD_NUMBER = 2;
  private long studentUserid_;
  /**
   * <code>int64 studentUserid = 2;</code>
   */
  public long getStudentUserid() {
    return studentUserid_;
  }

  public static final int STAFFUSERID_FIELD_NUMBER = 3;
  private long staffUserid_;
  /**
   * <code>int64 staffUserid = 3;</code>
   */
  public long getStaffUserid() {
    return staffUserid_;
  }

  public static final int OPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object option_;
  /**
   * <code>string option = 4;</code>
   */
  public java.lang.String getOption() {
    java.lang.Object ref = option_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      option_ = s;
      return s;
    }
  }
  /**
   * <code>string option = 4;</code>
   */
  public com.google.protobuf.ByteString
      getOptionBytes() {
    java.lang.Object ref = option_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      option_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WITHEMAIL_FIELD_NUMBER = 5;
  private boolean withEmail_;
  /**
   * <code>bool withEmail = 5;</code>
   */
  public boolean getWithEmail() {
    return withEmail_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTemplateCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, templateCode_);
    }
    if (studentUserid_ != 0L) {
      output.writeInt64(2, studentUserid_);
    }
    if (staffUserid_ != 0L) {
      output.writeInt64(3, staffUserid_);
    }
    if (!getOptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, option_);
    }
    if (withEmail_ != false) {
      output.writeBool(5, withEmail_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTemplateCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, templateCode_);
    }
    if (studentUserid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, studentUserid_);
    }
    if (staffUserid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, staffUserid_);
    }
    if (!getOptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, option_);
    }
    if (withEmail_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, withEmail_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpctest1.NotificationRequest)) {
      return super.equals(obj);
    }
    com.example.grpctest1.NotificationRequest other = (com.example.grpctest1.NotificationRequest) obj;

    boolean result = true;
    result = result && getTemplateCode()
        .equals(other.getTemplateCode());
    result = result && (getStudentUserid()
        == other.getStudentUserid());
    result = result && (getStaffUserid()
        == other.getStaffUserid());
    result = result && getOption()
        .equals(other.getOption());
    result = result && (getWithEmail()
        == other.getWithEmail());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPLATECODE_FIELD_NUMBER;
    hash = (53 * hash) + getTemplateCode().hashCode();
    hash = (37 * hash) + STUDENTUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStudentUserid());
    hash = (37 * hash) + STAFFUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStaffUserid());
    hash = (37 * hash) + OPTION_FIELD_NUMBER;
    hash = (53 * hash) + getOption().hashCode();
    hash = (37 * hash) + WITHEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWithEmail());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpctest1.NotificationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpctest1.NotificationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.NotificationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpctest1.NotificationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpctest1.NotificationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpctest1.NotificationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpctest1.NotificationRequest)
      com.example.grpctest1.NotificationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_NotificationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_NotificationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpctest1.NotificationRequest.class, com.example.grpctest1.NotificationRequest.Builder.class);
    }

    // Construct using com.example.grpctest1.NotificationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      templateCode_ = "";

      studentUserid_ = 0L;

      staffUserid_ = 0L;

      option_ = "";

      withEmail_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpctest1.NotificationServiceOuterClass.internal_static_com_example_grpctest1_NotificationRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpctest1.NotificationRequest getDefaultInstanceForType() {
      return com.example.grpctest1.NotificationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpctest1.NotificationRequest build() {
      com.example.grpctest1.NotificationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpctest1.NotificationRequest buildPartial() {
      com.example.grpctest1.NotificationRequest result = new com.example.grpctest1.NotificationRequest(this);
      result.templateCode_ = templateCode_;
      result.studentUserid_ = studentUserid_;
      result.staffUserid_ = staffUserid_;
      result.option_ = option_;
      result.withEmail_ = withEmail_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpctest1.NotificationRequest) {
        return mergeFrom((com.example.grpctest1.NotificationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpctest1.NotificationRequest other) {
      if (other == com.example.grpctest1.NotificationRequest.getDefaultInstance()) return this;
      if (!other.getTemplateCode().isEmpty()) {
        templateCode_ = other.templateCode_;
        onChanged();
      }
      if (other.getStudentUserid() != 0L) {
        setStudentUserid(other.getStudentUserid());
      }
      if (other.getStaffUserid() != 0L) {
        setStaffUserid(other.getStaffUserid());
      }
      if (!other.getOption().isEmpty()) {
        option_ = other.option_;
        onChanged();
      }
      if (other.getWithEmail() != false) {
        setWithEmail(other.getWithEmail());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpctest1.NotificationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpctest1.NotificationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object templateCode_ = "";
    /**
     * <code>string templateCode = 1;</code>
     */
    public java.lang.String getTemplateCode() {
      java.lang.Object ref = templateCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string templateCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateCodeBytes() {
      java.lang.Object ref = templateCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string templateCode = 1;</code>
     */
    public Builder setTemplateCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      templateCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string templateCode = 1;</code>
     */
    public Builder clearTemplateCode() {
      
      templateCode_ = getDefaultInstance().getTemplateCode();
      onChanged();
      return this;
    }
    /**
     * <code>string templateCode = 1;</code>
     */
    public Builder setTemplateCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      templateCode_ = value;
      onChanged();
      return this;
    }

    private long studentUserid_ ;
    /**
     * <code>int64 studentUserid = 2;</code>
     */
    public long getStudentUserid() {
      return studentUserid_;
    }
    /**
     * <code>int64 studentUserid = 2;</code>
     */
    public Builder setStudentUserid(long value) {
      
      studentUserid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 studentUserid = 2;</code>
     */
    public Builder clearStudentUserid() {
      
      studentUserid_ = 0L;
      onChanged();
      return this;
    }

    private long staffUserid_ ;
    /**
     * <code>int64 staffUserid = 3;</code>
     */
    public long getStaffUserid() {
      return staffUserid_;
    }
    /**
     * <code>int64 staffUserid = 3;</code>
     */
    public Builder setStaffUserid(long value) {
      
      staffUserid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 staffUserid = 3;</code>
     */
    public Builder clearStaffUserid() {
      
      staffUserid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object option_ = "";
    /**
     * <code>string option = 4;</code>
     */
    public java.lang.String getOption() {
      java.lang.Object ref = option_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        option_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string option = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOptionBytes() {
      java.lang.Object ref = option_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        option_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string option = 4;</code>
     */
    public Builder setOption(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      option_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string option = 4;</code>
     */
    public Builder clearOption() {
      
      option_ = getDefaultInstance().getOption();
      onChanged();
      return this;
    }
    /**
     * <code>string option = 4;</code>
     */
    public Builder setOptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      option_ = value;
      onChanged();
      return this;
    }

    private boolean withEmail_ ;
    /**
     * <code>bool withEmail = 5;</code>
     */
    public boolean getWithEmail() {
      return withEmail_;
    }
    /**
     * <code>bool withEmail = 5;</code>
     */
    public Builder setWithEmail(boolean value) {
      
      withEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool withEmail = 5;</code>
     */
    public Builder clearWithEmail() {
      
      withEmail_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpctest1.NotificationRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpctest1.NotificationRequest)
  private static final com.example.grpctest1.NotificationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpctest1.NotificationRequest();
  }

  public static com.example.grpctest1.NotificationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotificationRequest>
      PARSER = new com.google.protobuf.AbstractParser<NotificationRequest>() {
    @java.lang.Override
    public NotificationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NotificationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NotificationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotificationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpctest1.NotificationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

