// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: templateService.proto

package com.example.grpctest1;

public interface TemplateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpctest1.TemplateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string notificationTo = 2;</code>
   */
  java.lang.String getNotificationTo();
  /**
   * <code>string notificationTo = 2;</code>
   */
  com.google.protobuf.ByteString
      getNotificationToBytes();
}
