// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: templateService.proto

package com.example.grpctest1;

public interface TemplateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpctest1.TemplateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string templateCode = 1;</code>
   */
  java.lang.String getTemplateCode();
  /**
   * <code>string templateCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemplateCodeBytes();

  /**
   * <code>int64 studentUserid = 2;</code>
   */
  long getStudentUserid();

  /**
   * <code>int64 staffUserid = 3;</code>
   */
  long getStaffUserid();

  /**
   * <code>string option = 4;</code>
   */
  java.lang.String getOption();
  /**
   * <code>string option = 4;</code>
   */
  com.google.protobuf.ByteString
      getOptionBytes();
}
